package sample.data.jpa.form;
// Imports ...

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

import com.fasterxml.jackson.annotation.JsonManagedReference;


//import org.springframework.lang.NonNull;


public class UserForm {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull
  @Column(name="mail")
  private String email;
  
  @NotNull
  private String name;

  @NotNull
  @Column(name="mdp")
  private String password;
  

public long getId() {
	return id;
}

public void setId(long id) {
	this.id = id;
}

public String getEmail() {
	return email;
}

public void setEmail(String email) {
	this.email = email;
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

//A revoir
//TODO
public String getPassword() {
	return password;
}

public void setPassword(String password) {
	this.password=password;
}

@Override
public String toString() {
	System.out.println(email);
	return   id + " " + name + " | " + email;
}

}