package sample.data.jpa.domain;
// Imports ...

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;

import com.fasterxml.jackson.annotation.JsonManagedReference;


//import org.springframework.lang.NonNull;

@Entity
@Table(name = "User")
public class User {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull//(message = "Email invalide")
  @Column(name="mail")
  private String email;
  
  @NotNull//(message = "Nom invalide")
  private String name;

  @NotNull//(message = "Mot de passe invalide")
  @Column(name="mdp")
  private String password;
  
//  @OneToMany(targetEntity=Appointment.class, mappedBy="us", cascade=CascadeType.ALL)
 // private List<Appointment> appoint = new ArrayList<Appointment>();
  // Public methods
  
  public User() { }

  public User(long id) { // Je vais peut-être te virer
    this.id = id;
  }
  
  public User(String email, String name, String password) {
    this.email = email;
    this.name = name;
    this.password = password;
  }

public long getId() {
	return id;
}

public void setId(long id) {
	this.id = id;
}

public String getEmail() {
	return email;
}

public void setEmail(String email) {
	this.email = email;
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

//A revoir
//TODO
public String getPassword() {
	return password;
}

public void setPassword(String password) {
	this.password=password;
}

@Override
public String toString() {
	System.out.println(email);
	return   id + " " + name + " | " + email;
}
/*@OneToMany(targetEntity=Appointment.class, mappedBy="us", cascade=CascadeType.ALL)
//@JsonManagedReference
@XmlElementWrapper(name = "appoints")
@XmlElement(name = "appoint")
public List<Appointment> getAppoint() {
	return appoint;
}

public void setAppoint(List<Appointment> appoint) {
	this.appoint = appoint;
}*/
  // Getter and setter methods
  // ...

//public User orElseThrow(Object object) {
//	// TODO Auto-generated method stub
//	return null;
//}

}